### ISSUE TITLE
[Security] Use a more secure system to store secret tokens

### ISSUE THREAD

**Issue by Shotman** [pwltr/tauthy#1]
According to that : https://github.com/pwltr/tauthy/blob/f7ab747c60307a618bbba7df450e8acc88857641/src/utils/index.ts#L24
I see the secret tokens used to generate the TOTP codes are stored in the webview localstorage, that's a big security issue since this localstorage can be accessed without opening the app so the codes are 100% exposed to any attacker or malware present on the system

I suggest using a more secure way of storing them, one would be the tauri-stronghold plugin coupled with either a master password or some kind of physical authentication (yubikey etc) and that could be done with the tauri-authentication plugin

**Comment by pwltr** [comment]
Hey @Shotman , thanks for checking out the repo and the great feedback! I really appreciate it and will get right on improving that.
