### ISSUE TITLE
[Feature]: Autotype feature ?

### ISSUE THREAD

**Issue by VPraharsha03** [pwltr/tauthy#117]
### Describe the problem

How about an auto-type feature is added which is similar to that of what [KeeWeb](https://github.com/keeweb/keeweb/wiki/Auto-Type) has (which was originated in `KeePass`) ? As a KeePass user, I feel It could be quite handy and easier to auto type than copy pasting TOTPs

**Comment by pwltr** [comment]
Hi @VPraharsha03 

Is [this](https://github.com/pwltr/tauthy/issues/183#issuecomment-1595796811) the kind of feature you were looking for? If not could you elaborate what you would be able to do?
