### ISSUE TITLE
[Feature]: Add option auto search after open tauthy

### ISSUE THREAD

**Issue by 3xploiton3** [pwltr/tauthy#183]
### Describe the problem

I always use 2fa with multiple accounts, please make it easier when opening tauthy after entering the password it immediately leads to the search field,

### Describe the solution

after open password make keyboard use search form, so we not touching the mouse

**Comment by pwltr** [comment]
Hey thanks, I'll look into improving UX for this use case.

**Comment by pwltr** [comment]
Improved keyboard UX [here](https://github.com/pwltr/tauthy/commit/b312e2d1f4a099d38a2d35dd5f8668a44cab9a1a).

It's now possible to search as soon as the window is focused. If there is only one result you can use `Ctrl + c` or `Cmd + c` to copy the token. `Escape` will reset the search filter.

https://github.com/pwltr/tauthy/assets/8538369/d0ac1a54-82cf-45e1-ab7f-e52ae10a5d41

Thanks for the suggestion!
