### ISSUE TITLE
[Bug]: Windows 10 saves secret tokens

### ISSUE THREAD

**Issue by realchandan** [pwltr/tauthy#185]
### Describe the bug

I recently installed tauthy (again) on windows 10, and I found something weird that I haven't seen before.
I see windows 10 shows me what I have put into the `Secret` field in the past.

I have cleared clipboard data, I am attaching a screenshot of the bug.

Is this intended behavior of the app, or Is this a windows bug/feature? Is there a way to by default prevent windows from saving tokens that could be put into the code itself?

![windows_bug](https://github.com/pwltr/tauthy/assets/93002151/d56e4307-adca-4db7-b483-ae694adcf1d7)

### Reproduce

I really don't know how!

### Tauthy version

v0.2.3

### Operating system

Windows 10

**Comment by pwltr** [comment]
Hey thanks for bringing this up, should be an easy fix.
