### ISSUE TITLE
[Feature]: copy code then minimize app

### ISSUE THREAD

**Issue by 3xploiton3** [pwltr/tauthy#191]
### Describe the problem

we always use click copy code then minimize app,

### Describe the solution

give us feature optional for minimize app after copy code OTP

**Comment by pwltr** [comment]
Sure can add a setting for this.

**Comment by pwltr** [comment]
Added under `Settings -> Appearance -> Minimize on copy`

<img width="377" alt="Screenshot 2023-08-05 at 18 22 39" src="https://github.com/pwltr/tauthy/assets/8538369/c71c1fa3-3423-4f1c-ac7e-5022a7d1e10f">
