### ISSUE TITLE
virustotal: Un_A.exe

### ISSUE THREAD

**Issue by 3xploiton3** [pwltr/tauthy#204]
https://www.virustotal.com/gui/file/4fba2291deaaef67ace206e72098c28fe69b907bb6be340

![image](https://github.com/pwltr/tauthy/assets/19517680/367c574e-3130-44e7-b9bd-cafb38c6e763)

**Comment by pwltr** [comment]
Any more details? What exactly is this report? Filename `Un_A.exe` seems unrelated to this app.
