### ISSUE TITLE
Alphabetic sort

### ISSUE THREAD

**Issue by realchandan** [pwltr/tauthy#74]
Hi there,

I use your app on day to day basis, I feel it would be much better if the 2fa codes were sorted by their respective account names, that would help nagivate easily when one has too many accounts!

Thanks

**Comment by pwltr** [comment]
Hi and thanks for the feedback. There is a rudimentary sort feature implemented right now. If you click on the icon in the header it should bring up an "A-Z" option there. Or are you looking for a different way to sort? There will be more options in the future, for example "sort by usage". If you have more ideas please share and I will include it.

**Comment by realchandan** [comment]
Hi there,

I didn't knew the feature existed, from now I would use A-Z sort.

and, thanks for creating this amazing tool.
